spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
